# Generated by Django 2.2.6 on 2019-11-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20191102_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
