# Generated by Django 2.2.6 on 2019-11-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_profesor_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCurso', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=20)),
                ('credito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPeriodo', models.CharField(max_length=4)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('horas', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profesor')),
            ],
        ),
    ]
